// ENVIRONMENT NEEDED TO SET UP THIS APPLICATION

// ACCOUNT_SID=
// API_KEY=
// API_KEY_SECRET=
// outgoingApplicationSid=
// APP_SID=
// PUSH_CREDENTIAL_SID=
// pushCredSid=
// outgoingAPP_SID=
// DATABASE_LOCAL=
// port=
// JWT_SECRET=
// JWT_COOKIE_EXPIRES_IN=
// JWT_EXPIRES_IN=

//FOR VOICE AND VIDEO CALL APP
// VOXIMPLANT_ACCOUNT_SID=
// VOXIMPLANT_API_KEY=f
// VOXIMPLANT_APP_ID=
